version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/improving-protocol-standards/src

    steps:
      - checkout

      - run:
          command: |
            sudo pip install pipenv
            pipenv install

      - run:
          name: run tests
          command: |
            pipenv run "python protocol.py"

      - store_artifacts:
          path: test-results
          destination: test-results
