version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/improving-protocol-standards

    steps:
      - checkout

      - run:
          command: |
            sudo pip install pipenv pytest mypy
            pipenv install

      - run:
          name: run tests
          command: |
            pipenv run pytest --junitxml=test-results/protocol-tests.xml src/protocol.py
	    mypy src/protocol.py --junit-xml test-results/protocol-typecheck.xml

      - store_artifacts:
          path: test-results
          destination: test-results
